apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  request: 
          LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBN
          QTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJD
          Z0tDQVFFQXd1SmVqNlNBNjJudWswVENvVEwxMW9MeHVncUZLL25TT00vMUZkUXE5cXFkCkoxUko1
          bGZqaWQ5eDdHTEhZU0w2S2JIUmR3SjZ3cVU4UmJhUUFoQlNCV2RZVXVlcURsT2pGZHZ6SUZCNWJ6
          TEgKWGhSYUFJTDZWZTJPc2VwVDFVaG5aclVpdHBobzVCa3FQK3hGc3IzQ3BkOEZ5VktRT0pKY2RB
          V2VxNnoxN1dOVwp5SmRpSkZzVCtoMTM5NGh5ZGNuZWtoNkV2RlFaV0QxQktjZTVpVWIxSm9qRUdK
          UmJ5WHgvL1J2R0w5VGZQaU1YCjQzUUtCbThUSjVXdUJxazNkd1RpYVhETGJUZnR1UnVCU2dPN09r
          czJaNW5kb3VuMHQ5ejlhRTZRN2RuSDFhN0oKQkxLMW5JcTIrY1FPMlpTelNOMC9JV3hpMWpMZFQw
          RXpFZmFmTitrK3ZRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQlgreGxxWVdP
          R2lXSnQ5NXBoWnFPL2ZXWEZyYWJsUWlkOEdlQTVnc0pabjdyQ2lSb0VOCmd1VWxubUFEdzFTOElK
          VWd0aFlMd25FbGZmZ0k3bGFIUDlHMnBWR3Q0TGd2cnFMVGFNQ3NtcXcxQkR1ZU9GYjgKNFlXUkli
          WjVKdzROOFV1dE1PRkVObEcwT1dkYlpxSGMxVitEN3JCcGp1SnhDbnhabG5qQVhMMXhnR2pGTXpJ
          UQp3Qk5nUzJuQUl2OXpQeEtFLzRIUWlueTVKU1ZMUXphR3FXcGZqQzVvN2xOL3lDRUlHM2FObE9t
          SThiVHoyRXhhCjN0c212TC9oL2Z2N2g0aS9uaVlreFhhTW1UaUJid3hDTHVSRnlFUFpEZ0tjcDJT
          Y3RqUk1IRnNNTkhxdjNqVVoKd3IzZmpDeWt6TTVPUVhPTVZSSlJld2ZzRERHQlVWWlFvVlk9Ci0t
          LS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth