apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx-configmap.yaml
  - nginx-ingress.yaml
  - nginx-serviceaccount.yaml
  - nginx-clusterrole.yaml
  - nginx-clusterrolebinding.yaml
  - nginx-role.yaml
  - nginx-rolebinding.yaml
  - nginx-validatingwebhookconfiguration.yaml
  - nginx-admission-webhook.yaml
  - nginx-namespace.yaml
  - nginx-gateway.yaml
  - nginx-gatewayclass.yaml
  - nginx-http-route.yaml
  - nginx-ingressclass.yaml
  - nginx-ingressclassparams.yaml
  - nginx-httproutebinding.yaml

commonLabels:
  app: nginx-ingress-controller
  version: v1.0.0
  environment: production


---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db/db-config.yaml
  - db/db-depl.yaml
  - db/db-service.yaml
  - message-broker/rabbitmq-config.yaml
  - message-broker/rabbitmq-depl.yaml
  - message-broker/rabbitmq-service.yaml 
  - nginx/nginx-depl.yaml
  - nginx/nginx-service.yaml


