---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  namespace: default
  name: developer
rules:  
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: [ "delete", "list", "create"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]


---
# dev-user-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1  
kind: RoleBinding
metadata:
  name: dev-user-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
subjects:
- kind: User
  name: dev-user
  apiGroup: rbac.authorization.k8s.io

